from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('getTeacher/', views.getTeacher, name = 'getTeacher'),
    path('applyTeacher/', views.applyTeacher, name = 'applyTeacher'),
    path('getApplicationByTeacher/', views.getApplicationByTeacher, name = 'getApplicationByTeacher'),
    path('acceptStu/', views.acceptStu, name = 'acceptStu'),
    path('refuseStu/', views.refuseStu, name = 'refuseStu'),
    path('addTeaQueue/', views.addTeaQueue, name = 'addTeaQueue'),
    path('storeTeaQueue/', views.storeTeaQueue, name = 'storeTeaQueue'),
    path('getTeaQueue/', views.getTeaQueue, name = 'getTeaQueue'),
    path('uploadfile/', views.uploadfile, name = 'uploadfile'),
    path('addWorkTitle/', views.addWorkTitle, name = 'addWorkTitle'),
    path('getRecordTitle/', views.getRecordTitle, name = 'getRecordTitle'),
    path('addRecordStu/', views.addRecordStu, name = 'addRecordStu'),
    path('getStudentStartbyTea/', views.getStudentStartbyTea, name = 'getStudentStartbyTea'),
    path('createUser/', views.createUser, name = 'createUser'),
    path('uploadAvater/', views.uploadAvater, name = 'uploadAvater'),
    path('getCurUserID/', views.getCurUserID, name = 'getCurUserID'),
    path('getUserAvaterByID/', views.getUserAvaterByID, name = 'getUserAvaterByID'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('getUser/', views.getUser, name = 'getUser'),
    path('getMyStudent/', views.getMyStudent, name = 'getMyStudent'),
    path('changeInfo/', views.changeInfo, name = 'changeInfo'),
    path('getStudentStartProcess/', views.getStudentStartProcess, name = 'getStudentStartProcess'),
    path('subTeacherProcess/', views.subTeacherProcess, name = 'subTeacherProcess'),
    path('getTeacherProcess/', views.getTeacherProcess, name = 'getTeacherProcess'),
    path('addRecordContent/', views.addRecordContent, name = 'addRecordContent'),
    path('addRecordIntroduction/', views.addRecordIntroduction, name = 'addRecordIntroduction'),
    path('validateUserName/', views.validateUserName, name = 'validateUserName'),
    path('initcheckman/', views.initcheckman, name = 'initcheckman'),
    path('checkUser/', views.checkUser, name = 'checkUser'),
    path('delUser/', views.delUser, name = 'delUser'),
    path('initFileMan/', views.initFileMan, name = 'initFileMan'),
    path('loginBacth/', views.loginBacth, name = 'loginBacth'),
    path('getStudentMediumbyTea/', views.getStudentMediumbyTea, name = 'getStudentMediumbyTea'),
    path('makeGreatPro/', views.makeGreatPro, name = 'makeGreatPro'),
    path('storeArchive/', views.storeArchive, name = 'storeArchive'),
    path('getStudentEndProcess/', views.getStudentEndProcess, name = 'getStudentEndProcess'),
    path('initHome/', views.initHome, name = 'initHome'),
    path('getStudentEndbyTea/', views.getStudentEndbyTea, name = 'getStudentEndbyTea'),
    path('getStudentMediumProcess/', views.getStudentMediumProcess, name = 'getStudentMediumProcess'),
]