# Generated by Django 3.1.2 on 2021-02-01 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210131_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='queue',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='requirement',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('check', models.BooleanField()),
                ('stu_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stus_app', to='backend.student')),
                ('tea_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teas_app', to='backend.teacher')),
            ],
        ),
    ]
