# Generated by Django 3.1.2 on 2021-02-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210201_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.TextField(default='无'),
        ),
    ]
