# Generated by Django 3.1.2 on 2021-02-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210201_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='queue',
            field=models.TextField(default='NULL', null=True),
        ),
    ]
