# Generated by Django 3.1.2 on 2021-02-02 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210201_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher_fol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_fol', to='backend.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='work',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workbystu', to='backend.work'),
        ),
    ]
