# Generated by Django 3.1.2 on 2021-02-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210203_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='process',
            field=models.CharField(choices=[('S', 'Start'), ('M', 'Middle'), ('E', 'End')], max_length=1, null=True),
        ),
    ]
