# Generated by Django 3.1.2 on 2021-02-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210205_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teas_record', to='backend.teacher'),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_point',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='middle_point',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_point',
            field=models.IntegerField(null=True),
        ),
    ]
