# Generated by Django 3.1.2 on 2021-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210205_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avater',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
