# Generated by Django 3.1.2 on 2021-03-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_user_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
