# Generated by Django 3.1.2 on 2021-03-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_record_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='end_point',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='middle_point',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_point',
            field=models.DateTimeField(null=True),
        ),
    ]
