# Generated by Django 3.1.2 on 2021-03-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210324_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
