# Generated by Django 3.1.2 on 2021-04-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valid',
            field=models.BooleanField(null=True),
        ),
    ]
