# Generated by Django 3.1.2 on 2021-04-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_archives'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='process',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
