# Generated by Django 3.1.2 on 2021-04-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_archives_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
