# Generated by Django 3.1.2 on 2021-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20210421_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='school',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='archives',
            name='uni',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
