# Generated by Django 3.1.2 on 2021-04-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20210422_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='backend.student'),
        ),
        migrations.AlterField(
            model_name='archives',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='backend.teacher'),
        ),
    ]
