# Generated by Django 3.1.2 on 2021-04-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20210422_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='great',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
