# Generated by Django 3.1.2 on 2021-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20210423_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni', models.CharField(max_length=40, null=True)),
                ('school', models.CharField(max_length=40, null=True)),
                ('now', models.IntegerField(null=True)),
            ],
        ),
    ]
